// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATA_DATAMESSAGE_H_
#define FLATBUFFERS_GENERATED_DATA_DATAMESSAGE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace DataMessage {

struct Timestamp;

struct Message;
struct MessageBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Timestamp FLATBUFFERS_FINAL_CLASS {
 private:
  int64_t seconds_;
  int32_t nanoseconds_;
  int32_t padding0__;

 public:
  Timestamp()
      : seconds_(0),
        nanoseconds_(0),
        padding0__(0) {
    (void)padding0__;
  }
  Timestamp(int64_t _seconds, int32_t _nanoseconds)
      : seconds_(flatbuffers::EndianScalar(_seconds)),
        nanoseconds_(flatbuffers::EndianScalar(_nanoseconds)),
        padding0__(0) {
    (void)padding0__;
  }
  int64_t seconds() const {
    return flatbuffers::EndianScalar(seconds_);
  }
  int32_t nanoseconds() const {
    return flatbuffers::EndianScalar(nanoseconds_);
  }
};
FLATBUFFERS_STRUCT_END(Timestamp, 16);

struct Message FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TIMESTAMP = 6,
    VT_PAYLOAD = 8,
    VT_PRIORITY = 10
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const DataMessage::Timestamp *timestamp() const {
    return GetStruct<const DataMessage::Timestamp *>(VT_TIMESTAMP);
  }
  const flatbuffers::String *payload() const {
    return GetPointer<const flatbuffers::String *>(VT_PAYLOAD);
  }
  int32_t priority() const {
    return GetField<int32_t>(VT_PRIORITY, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<DataMessage::Timestamp>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyString(payload()) &&
           VerifyField<int32_t>(verifier, VT_PRIORITY, 4) &&
           verifier.EndTable();
  }
};

struct MessageBuilder {
  typedef Message Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(Message::VT_ID, id, 0);
  }
  void add_timestamp(const DataMessage::Timestamp *timestamp) {
    fbb_.AddStruct(Message::VT_TIMESTAMP, timestamp);
  }
  void add_payload(flatbuffers::Offset<flatbuffers::String> payload) {
    fbb_.AddOffset(Message::VT_PAYLOAD, payload);
  }
  void add_priority(int32_t priority) {
    fbb_.AddElement<int32_t>(Message::VT_PRIORITY, priority, 0);
  }
  explicit MessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline flatbuffers::Offset<Message> CreateMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const DataMessage::Timestamp *timestamp = nullptr,
    flatbuffers::Offset<flatbuffers::String> payload = 0,
    int32_t priority = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_priority(priority);
  builder_.add_payload(payload);
  builder_.add_timestamp(timestamp);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<Message> CreateMessageDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const DataMessage::Timestamp *timestamp = nullptr,
    const char *payload = nullptr,
    int32_t priority = 0) {
  auto payload__ = payload ? _fbb.CreateString(payload) : 0;
  return DataMessage::CreateMessage(
      _fbb,
      id,
      timestamp,
      payload__,
      priority);
}

inline const DataMessage::Message *GetMessage(const void *buf) {
  return flatbuffers::GetRoot<DataMessage::Message>(buf);
}

inline const DataMessage::Message *GetSizePrefixedMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<DataMessage::Message>(buf);
}

inline bool VerifyMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<DataMessage::Message>(nullptr);
}

inline bool VerifySizePrefixedMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<DataMessage::Message>(nullptr);
}

inline void FinishMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<DataMessage::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<DataMessage::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DataMessage

#endif  // FLATBUFFERS_GENERATED_DATA_DATAMESSAGE_H_
